---
title: "Styringsinformasjon for ny sykepengeløsning"
date-modified: last-modified
format:
    html:
        echo: false
        self-contained: true
        theme:
            - custom.scss
---



```{python}
import datetime
from datetime import date
import pandas as pd
import warnings
import os
import plotly.graph_objects as go
from dotenv import load_dotenv
from google.cloud import bigquery
import plotly.express as px

warnings.filterwarnings(
    "ignore", "Your application has authenticated using end user credentials"
)
warnings.filterwarnings(
    "ignore", "A progress bar was requested, but there was an error loading the tqdm library."
)

load_dotenv(override=True)
LOCATION = "europe-north1"
PROJECT = os.environ["GCP_TEAM_PROJECT_ID"]

client = bigquery.Client(location=LOCATION, project=PROJECT)

norsk_dag = {
    "Monday": "Mandag",
    "Tuesday": "Tirsdag",
    "Wednesday": "Onsdag",
    "Thursday": "Torsdag",
    "Friday": "Fredag",
    "Saturday": "Lørdag",
    "Sunday": "Søndag",
}

månednavn = {
    1: "Januar",
    2: "Februar",
    3: "Mars",
    4: "April",
    5: "Mai",
    6: "Juni",
    7: "Juli",
    8: "August",
    9: "September",
    10: "Oktober",
    11: "November",
    12: "Desember",
}

```

:::: {#section-intro}

::: {#section-intro-content}

### Om fortellingen

Datafortellingen har som hensikt å gi grunnlag for bedre og mer presise prioriteringer knyttet til saksbehandling i nytt behandlingssystem for sykepenger. 

I fortellingen presenteres dataen kronologisk gjennom saksbehandlingsforløpet, fra en søknad om sykepenger er sendt, til vedtaket er fattet eller forkastet og sendt- eller ikke sendt til utbetaling.

::: {.callout-note collapse="true" appearance="minimal"}
## Mer om dataen som presenteres

Dataen som presenteres stammer kun fra nytt saksbehandlingssystem. Årsaken til dette er at vi har lite eller mangelfull data på saksbehandling av sykepenger i eldre behandlingssystemer. Samtidig har ikke PO Helse selv eierskap til dette, og derfor være sikre på at dataen stemmer.

Siden dataen er ment for å gjøre prioriteringer og strategiske veivalg i forbindelse med saksbehandling er det avgjørende at det som presenteres stemmer overens med det som faktisk skjer.

Foreløpig presenteres det i denne fortellingen data på innsendte søknader, fattede vedtak og forkastede vedtak. Det gjenstår fortsatt en del hendelsespunkter som omfatter for eksempel inntektsmeldinger, frister etc. Planen er å få dette på plass over tid.
:::

::: {.callout-note collapse="true" appearance="minimal"}
## Mer om teamet

Team Hvilepuls fra PO Helse har designet og drifter denne fortellingen. Teamet består av medlemmer forskjellige fagfelt, hentet fra ulike teams i produktområdet.

Vi ønsker å eie, drifte og formidle dataen vi selv genererer. På denne måten forsøker vi å sikre at dataen som formidles, stemmer overens med det som faktisk skjer.

[Les mer om teamet i Teamkatalogen.](https://teamkatalog.nav.no/team/ea2ba8f9-b956-4d78-857e-93e547449fc5){.external target="_blank"}
:::

:::

::::


:::: {#section1}

::: {#section1-content}


### 1# Søknader

#

Gjelder søknader (med unntak av kode 6) som er innsendt digitalt og søknader for digitaliserte papirsykmeldinger. 

Nøkkeltallene viser totaloversikten over innsendte og korrigerte søknader samlet. Under viser grafen (innsendt per måned) hvor stor andel som er korrigert.


::: {.nokkeltall}

```{python}
# | class: nokkeltall
import datetime as dt

current_date = dt.datetime.now().date()
formatted_date = current_date.strftime("%d. %B %Y").replace(current_date.strftime("%B"), current_date.strftime("%B").lower())

print(f"Innsendte søknader per {formatted_date}")

```

:::

```{python}

def antall_for_n_uker_siden(antall_uker_siden, timestamp_felt, tabell):
    QUERY = f"""--sql
    SELECT
        COUNT(*)
    FROM `{tabell}`
    WHERE DATE_TRUNC(DATE({timestamp_felt}, 'Europe/Oslo'), WEEK(MONDAY)) >= DATE_TRUNC(DATE_SUB(DATE(CURRENT_TIMESTAMP(), 'Europe/Oslo'), INTERVAL {str(antall_uker_siden)} WEEK), WEEK(MONDAY))
    AND DATE_TRUNC(DATE({timestamp_felt}, 'Europe/Oslo'), WEEK(MONDAY)) < DATE_TRUNC(DATE_SUB(DATE(CURRENT_TIMESTAMP(), 'Europe/Oslo'), INTERVAL {str(antall_uker_siden)} - 1 WEEK), WEEK(MONDAY))
    """

    query_job = client.query(QUERY)
    rows = query_job.result()

    # get first value in first row of RowIterator
    return [row[0] for row in rows][0]
```

:::: {.nokkeltallboks-layout}

```{python}
# | class: nokkeltallboks-innhold

value = antall_for_n_uker_siden(2, "soknad_mottatt", "styringsinfo_dataset.styringsinfo_sendt_soknad_view")
print(f"{value}\nto uker siden")
```


```{python}
# | class: nokkeltallboks-innhold

value = antall_for_n_uker_siden(1, "soknad_mottatt", "styringsinfo_dataset.styringsinfo_sendt_soknad_view")
print(f"{value}\nforrige uke")
```


```{python}
# | class: nokkeltallboks-innhold

value = antall_for_n_uker_siden(0, "soknad_mottatt", "styringsinfo_dataset.styringsinfo_sendt_soknad_view")
print(f"{value}\ndenne uken")
```

::::

```{python}

# | class: no-rows

current_month = datetime.datetime.now().month
current_year = datetime.datetime.now().year

QUERY = f"""
    SELECT
        EXTRACT(DATE FROM soknad_mottatt AT TIME ZONE 'Europe/Oslo') AS date,
        DATE_TRUNC(EXTRACT(DATE FROM soknad_mottatt AT TIME ZONE 'Europe/Oslo'), WEEK(MONDAY)) as week,
        DATE_TRUNC(EXTRACT(DATE FROM soknad_mottatt AT TIME ZONE 'Europe/Oslo'), MONTH) as month,
        korrigerende,
        COUNT(*) as Totalt
    FROM `styringsinfo_dataset.styringsinfo_sendt_soknad_view`
    WHERE EXTRACT(YEAR FROM soknad_mottatt AT TIME ZONE 'Europe/Oslo') = {current_year}
        AND EXTRACT(MONTH FROM soknad_mottatt AT TIME ZONE 'Europe/Oslo') <= {current_month}
    GROUP BY date, week, month, korrigerende
    ORDER BY date ASC, korrigerende ASC
"""

query_job = client.query(QUERY)

df_days: pd.DataFrame = query_job.to_dataframe()
df_days_førstegangs = df_days[df_days.korrigerende == False]
df_days_korrigerende = df_days[df_days.korrigerende == True]

df_weeks = df_days.groupby(["week", "korrigerende"], as_index=False)["Totalt"].sum()
df_weeks_førstegang = df_weeks[df_weeks.korrigerende == False]
df_weeks_korrigerende = df_weeks[df_weeks.korrigerende == True]

df_months = df_days.groupby(["month", "korrigerende"], as_index=False)["Totalt"].sum()
df_months_førstegang = df_months[df_months.korrigerende == False]
df_months_korrigerende = df_months[df_months.korrigerende == True]

fig = go.Figure()
fig.add_traces(data = [
    go.Bar(
        x=df_months_førstegang.month,
        y=df_months_førstegang.Totalt,
        name="Førstegangs",
        visible=True,
        marker_color = 'rgba(176, 193, 200, 1)',
    ),
    go.Bar(
        x=df_months_korrigerende.month,
        y=df_months_korrigerende.Totalt,
        name="Korrigerende",
        visible=True,
        marker_color = 'rgba(240, 202, 43, 1)',
    ),    
    go.Bar(
        x=df_weeks_førstegang.week,
        y=df_weeks_førstegang.Totalt,
        name="Førstegangs",
        visible=False,
        marker_color = 'rgba(176, 193, 200, 1)',
    ),
    go.Bar(
        x=df_weeks_korrigerende.week,
        y=df_weeks_korrigerende.Totalt,
        name="Korrigerende",
        visible=False,
        marker_color = 'rgba(240, 202, 43, 1)',
    ),
    go.Bar(
        x=df_days_førstegangs.date,
        y=df_days_førstegangs.Totalt,
        name="Førstegangs",
        visible=False,
        marker_color = 'rgba(176, 193, 200, 1)',
    ),
    go.Bar(
        x=df_days_korrigerende.date,
        y=df_days_korrigerende.Totalt,
        name="Korrigerende",
        visible=False,
        marker_color = 'rgba(240, 202, 43, 1)',
    ),

])

BUTTON_CONFIG = {
    "active": 0,
    "type": "buttons",
    "direction": "right",
    "showactive": True,
    "x": 0,
    "xanchor": "left",
    "y": 1,
    "yanchor": "bottom",
    "font": {"size": 14},
}

fig.update_layout(barmode='stack', updatemenus=[
    dict(
        buttons=list([
            dict(
                args= [{"visible": [True, True, False, False, False, False]}],
                label="Måneder",
                method="restyle"
            ),
            dict(
                args= [{"visible": [False, False, True, True, False, False]}],
                label="Uker",
                method="restyle"
            ),
            dict(
                args= [{"visible": [False, False, False, False, True, True]}],
                label="Dager",
                method="restyle"
            )
        ]),
        ** BUTTON_CONFIG
    )
])

fig.show()
```

```{python}
def fig_antall_med_glidende_gjennomsnitt(tittel, timestamp_felt, tabell):
    from plotly.subplots import make_subplots

    # SQL query to count number of rows per day and calculate moving averages
    QUERY = f"""
    SELECT 
    date, 
    count,
    AVG(count) OVER (
        ORDER BY date
        ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
    ) AS moving_7_day_avg,
    AVG(count) OVER (
        ORDER BY date
        ROWS BETWEEN 27 PRECEDING AND CURRENT ROW
    ) AS moving_28_day_avg
    FROM (
        SELECT date_range.date AS date, IFNULL(original_table.count, 0) AS count
            FROM (
                SELECT *
                FROM UNNEST(GENERATE_DATE_ARRAY('2023-03-01', CURRENT_DATE())) AS date
            ) AS date_range
        LEFT JOIN (
        SELECT
            DATE({timestamp_felt}) AS date,
            COUNT(*) AS count
        FROM
            `{tabell}`
        GROUP BY
            DATE({timestamp_felt})
            ) AS original_table
        ON date_range.date = original_table.date
    )
    WHERE date > '2023-03-01'
    ORDER BY 
    date
    """

    query_job = client.query(QUERY)

    df: pd.DataFrame = query_job.to_dataframe()

    fig = go.Figure()

    # Add bar chart for daily counts
    fig.add_trace(
        go.Bar(x=df["date"], y=df["count"], name="Antall per dag")
    )

    # Add lines for moving averages
    fig.add_trace(
        go.Scatter(x=df["date"], y=df["moving_7_day_avg"], name="Snitt over 7 dager")
    )
    fig.add_trace(
        go.Scatter(x=df["date"], y=df["moving_28_day_avg"], name="Snitt over 28 dager")
    )

    # Set x and y axis labels
    fig.update_layout(
        title_text=tittel,
        xaxis_title="Dato",
        yaxis_title="Antall per dag",
    )

    return fig
```

```{python}
fig = fig_antall_med_glidende_gjennomsnitt(
    "Antall mottatte søknader per dag og 7- og 28-dagers glidende gjennomsnitt",
    "soknad_mottatt",
    "styringsinfo_dataset.styringsinfo_sendt_soknad_view",
    )
# Show the figure
fig.show()
```

:::

::::


:::: {#section2}

::: {#section2-content}

### 2# Avklarte vedtaksperioder

#

En vedtaksperiode er i utgangspunktet en periode den sykmeldte har søkt om sykepenger for, men kan også påvirkes av tilleggsinformasjon fra arbeidsgiver og saksbehandler.

NAV kan avklare at det skal utbetales sykepenger for perioden, men det kan også avklares til å medføre ingen utbetaling, eksempelvis om en periode ligger innenfor arbeidsgiverperioden.

Avklarte vedtaksperioder som vises, gjelder bare for de søknadene som håndteres i ny sykepengeløsning. Per september 2023 omfatter dette arbeidstakere, med unntak av kode 6 (ikke frilansere, næringsdrivende etc.).

#

::: {.nokkeltall}

```{python}
# | class: nokkeltall
import datetime as dt

current_date = dt.datetime.now().date()
formatted_date = current_date.strftime("%d. %B %Y").replace(current_date.strftime("%B"), current_date.strftime("%B").lower())

print(f"Nøkkeltall per {formatted_date}")

```

:::

::: {.nokkeltallboks-layout}

```{python}
# | class: nokkeltallboks-innhold-hvit
value = antall_for_n_uker_siden(2, "vedtak_fattet", "styringsinfo_dataset.styringsinfo_vedtak_fattet_view")
print(f"{value}\navklart to uker siden")

```


```{python}
# | class: nokkeltallboks-innhold-hvit

value = antall_for_n_uker_siden(1, "vedtak_fattet", "styringsinfo_dataset.styringsinfo_vedtak_fattet_view")
print(f"{value}\navklart forrige uke")
```


```{python}
# | class: nokkeltallboks-innhold-hvit

value = antall_for_n_uker_siden(0, "vedtak_fattet", "styringsinfo_dataset.styringsinfo_vedtak_fattet_view")
print(f"{value}\navklart denne uken")
```

:::

#

```{python}

# | class: no-rows
import datetime
import plotly.graph_objects as go

current_month = datetime.datetime.now().month
current_year = datetime.datetime.now().year

QUERY = f"""
    SELECT
        EXTRACT(YEAR FROM vedtak_fattet AT TIME ZONE 'Europe/Oslo') AS year,
        EXTRACT(MONTH FROM vedtak_fattet AT TIME ZONE 'Europe/Oslo') AS month,
        IF(utbetaling_id IS NOT NULL, true, false) AS har_utbetalingslenke,
        COUNT(*) as Totalt
    FROM `styringsinfo_dataset.styringsinfo_vedtak_fattet_view`
    WHERE EXTRACT(YEAR FROM vedtak_fattet AT TIME ZONE 'Europe/Oslo') = {current_year}
        AND EXTRACT(MONTH FROM vedtak_fattet AT TIME ZONE 'Europe/Oslo') <= {current_month}
    GROUP BY year, month, har_utbetalingslenke
    ORDER BY year DESC, month DESC
"""

query_job = client.query(QUERY)

df_months : pd.DataFrame = query_job.to_dataframe()
df_months_med_utbetaling = df_months[df_months.har_utbetalingslenke == True]
df_months_uten_utbetaling = df_months[df_months.har_utbetalingslenke == False]

# Create a new plotly figure
fig = go.Figure()

fig.add_trace(go.Bar(
    x=[f"{row['year']}-{row['month']:02}" for _, row in df_months_med_utbetaling.iterrows()],
    y=df_months_med_utbetaling['Totalt'],
    text=df_months_med_utbetaling['Totalt'],
    textposition='auto',
    name = "Med utbetaling",
    marker_color = 'rgba(0, 64, 0, 1)',
    marker_line_width = 1, 
    opacity = 1
))
fig.add_trace(go.Bar(
    x=[f"{row['year']}-{row['month']:02}" for _, row in df_months_uten_utbetaling.iterrows()],
    y=df_months_uten_utbetaling['Totalt'],
    text=df_months_uten_utbetaling['Totalt'],
    textposition='auto',
    name = "Uten utbetaling",
    marker_color = 'rgba(176, 193, 200, 1)',
    marker_line_width = 1, 
    opacity = 1
))


fig.update_layout(
    barmode="stack",
    title="Avklarte vedtaksperioder per måned med og uten utbetaling",
    xaxis_title="Måned",
    yaxis_title="Antall avklarte vedtaksperioder",
    xaxis_tickangle=-45,
    paper_bgcolor='rgba(0,0,0,0)',
    plot_bgcolor='rgba(0,0,0,0)',
)

fig.show()

```

```{python}
fig = fig_antall_med_glidende_gjennomsnitt(
    "Antall avklarte vedtaksperioder per dag og 7- og 28-dagers glidende gjennomsnitt",
    "vedtak_fattet",
    "styringsinfo_dataset.styringsinfo_vedtak_fattet_view",
    )

fig.update_layout(
    paper_bgcolor='rgba(0,0,0,0)',
    plot_bgcolor='rgba(0,0,0,0)',
)

# Show the figure
fig.show()
```

#

:::

::::

:::: {#section3}

::: {#section3-content}

### 3# Behandlingstid av søknader

#

Vi ser nå på alle søknader som det ble fattet vedtak på i løpet av en uke, og betrakter hvor mange dager det gikk fra vi mottok søknaden til vedtaket ble fattet.

- Nøkkeltallene viser antall søknader som det ble fattet vedtak på totalt, hvor mange av dem som ble behandlet på under et døgn, samt søknader det har tatt mer enn 90 dager å behandle

- For behandlingstid mellom 1 og 90 dager viser grafen fordelingen

#

```{python}

QUERY = f"""
SELECT COUNT(*) AS antall_vedtak, dager_brukt, DATE_TRUNC(vedtak_fattet_dato, WEEK(MONDAY)) as week
    FROM `styringsinfo_dataset.styringsinfo_vedtak_tidsbruk`
    WHERE vedtak_fattet_dato >= CURRENT_DATE() - 21
    AND har_utbetaling = true
    GROUP BY dager_brukt, week
    ORDER BY dager_brukt desc
"""

query_job = client.query(QUERY)

df: pd.DataFrame = query_job.to_dataframe()
uker = sorted(df["week"].unique(), reverse=True)
i_dag=date.today()
inneværende_uke = uker[0] if len(uker) > 0 else i_dag
forrige_uke = uker[1] if len(uker) > 1 else inneværende_uke
to_uker_siden = uker[2] if len(uker) > 2 else forrige_uke

df_inneværende_uke = df[df.week == inneværende_uke]

```

:::: {.nokkeltallboks-layout}

```{python}
# | class: nokkeltallboks-innhold
value = df_inneværende_uke["antall_vedtak"].values.sum()
print(f"{value}\nTotalt")

```


```{python}
# | class: nokkeltallboks-innhold
value = df_inneværende_uke.query("dager_brukt == 0")["antall_vedtak"].values.sum()
print(f"{value}\nUnder en dag")

```


```{python}
# | class: nokkeltallboks-innhold
value = df_inneværende_uke.query("dager_brukt > 90")["antall_vedtak"].values.sum()
print(f"{value}\nMer enn 90 dager")

```

::::

```{python}

fig = px.bar(df_inneværende_uke.query("dager_brukt > 0 & dager_brukt <= 90"), x="dager_brukt", y ="antall_vedtak", labels={ "dager_brukt": "Dager brukt", "antall_vedtak": "Antall søknader" })

fig.update_layout(
    xaxis_title="Dager brukt",
    xaxis_tick0=1,
    yaxis_title="Antall søknader",
    xaxis_tickangle=-45,
    paper_bgcolor='rgba(0,0,0,0)',
    plot_bgcolor='rgba(0,0,0,0)'
)

fig.show()

```

#

:::

::::

:::: {#section4}

::: {#section4-content}

### 4# Forkastede vedtaksperioder

#

En forkastet vedtaksperiode betyr at saksbehandlingssystemet har vurdert at perioden det søkes for ikke kan behandles i speil. Det trenger ikke nødvendigvis medføre at det opprettes gosys-oppgaver for de tilhørende søknadene. Det opprettes ikke oppgaver for korte perioder som er innenfor arbeidsgiverperioden. 

#

:::: {.nokkeltallboks-layout}

```{python}
# | class: nokkeltallboks-innhold
value = antall_for_n_uker_siden(2, "vedtak_forkastet", "styringsinfo_dataset.styringsinfo_vedtak_forkastet_view")
print(f"{value}\nto uker siden")

```


```{python}
# | class: nokkeltallboks-innhold

value = antall_for_n_uker_siden(1, "vedtak_forkastet", "styringsinfo_dataset.styringsinfo_vedtak_forkastet_view")
print(f"{value}\nforrige uke")
```


```{python}
# | class: nokkeltallboks-innhold

value = antall_for_n_uker_siden(0, "vedtak_forkastet", "styringsinfo_dataset.styringsinfo_vedtak_forkastet_view")
print(f"{value}\ndenne uken")
```


::::

#

```{python}

# | class: no-rows
import datetime
import plotly.graph_objects as go

current_month = datetime.datetime.now().month
current_year = datetime.datetime.now().year

QUERY = f"""
    SELECT
        EXTRACT(YEAR FROM vedtak_forkastet AT TIME ZONE 'Europe/Oslo') AS year,
        EXTRACT(MONTH FROM vedtak_forkastet AT TIME ZONE 'Europe/Oslo') AS month,
        COUNT(*) as Totalt
    FROM `styringsinfo_dataset.styringsinfo_vedtak_forkastet_view`
    WHERE EXTRACT(YEAR FROM vedtak_forkastet AT TIME ZONE 'Europe/Oslo') = {current_year}
        AND EXTRACT(MONTH FROM vedtak_forkastet AT TIME ZONE 'Europe/Oslo') <= {current_month}
    GROUP BY year, month
    ORDER BY year DESC, month DESC;
"""

query_job = client.query(QUERY)

df_months = query_job.to_dataframe()

# Create a new plotly figure
fig = go.Figure()

fig.add_trace(go.Bar(
    x=[f"{row['year']}-{row['month']:02}" for _, row in df_months.iterrows()],
    y=df_months['Totalt'],
    text=df_months['Totalt'],
    textposition='auto',
))

fig.update_traces(marker_color = 'rgba(176, 193, 200, 1)',
                  marker_line_width = 1, opacity = 1)

fig.update_layout(
    title="Forkastede vedtaksperioder per måned",
    xaxis_title="Måned",
    yaxis_title="Antall",
    xaxis_tickangle=-45,
    paper_bgcolor='rgba(0,0,0,0)',
)

fig.show()

```

#
```{python}
import datetime as dt

print(f"Sist oppdatert: {dt.datetime.now()}")
```


:::

::::