name: main
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'
      - 'Makefile'
      - 'env.example'
      - '.github/workflows/alerts.yml'
      - 'deploy/alerts.yml'

jobs:
  build:
    permissions:
      contents: "read"
      id-token: "write"
    name: build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: 'tbd'
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deployDevRunOnce:
    name: deploy to dev to run once
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: deploy/naisjob.yml
          IMAGE: ${{ needs.build.outputs.image }}
          VARS: deploy/dev-run-once.yml

  deployDevRunOnSchedule:
    name: deploy to dev run on schedule
    needs: [build, deployDevRunOnce]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: deploy/naisjob.yml
          IMAGE: ${{ needs.build.outputs.image }}
          VARS: deploy/dev-run-on-schedule.yml

  deployProdRunOnce:
    name: deploy to prod to run once
    needs: [build, deployDevRunOnce]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: deploy/naisjob.yml
          IMAGE: ${{ needs.build.outputs.image }}
          VARS: deploy/prod-run-once.yml

  deployProdRunOnSchedule:
    name: deploy to prod run on schedule
    needs: [build, deployProdRunOnce]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: deploy/naisjob.yml
          IMAGE: ${{ needs.build.outputs.image }}
          VARS: deploy/prod-run-on-schedule.yml